USE ArtPlatformDB;
INSERT INTO Team (`team_id`, `name`, `contact_info`, `team_type`, `team_lead_id`) VALUES
('1', 'Affecti sunt in eadem causa sunt, qua ante quam nati, et ad tranquillitatem ferant, quid est cur dub', '2922 Christians Court, Stamford, Connecticut, United States, 06912', 'Operations Team', '2'),
('2', 'Voluptate quaeri, de qua Epicurus quidem ita dicit, omnium rerum.', '4261 Santa Rita Way, Orlando, Florida, United States, 32825', 'IT Team', '6'),
('3', 'Ut sine cura metuque vivamus.', '1796 Westchester Way, Sacramento, California, United States, 95852', 'IT Team', '6'),
('4', 'Hic noster labor in varias reprehensiones incurreret. Nam quibusdam, et iis quidem non admodum flagi', '10327 Palmetto Drive, Cincinnati, Ohio, United States, 45243', 'Finance Team', '1'),
('5', 'Vel, si suas habent, illas non magnopere desiderent. Qui autem ita frui volunt voluptatibus, ut null', '12176 Adelphi Avenue, Arlington, Texas, United States, 76011', 'Marketing Team', '8'),
('6', 'Autem summa voluptas est, ut necessariae nec opera multa nec impensa expleantur; ne naturales quidem', '12909 Tidewater Terrace, Fort Worth, Texas, United States, 76115', 'Design Team', '4'),
('7', 'Geometrica discere maluisset quam illum etiam.', '8881 Piper Place, Portsmouth, New Hampshire, United States, 00214', 'Legal Team', '8'),
('8', 'Imperii. Quid? T. Torquatus, is qui consul cum Cn. Octavio fuit, cum illam.', '5301 Demoss Court, Des Moines, Iowa, United States, 50315', 'Sales Team', '2'),
('9', 'Sensibus; qui si omnes atomi declinabunt, nullae umquam cohaerescent, sive aliae declinabunt, aliae ', '14424 Matthew Avenue, Olympia, Washington, United States, 98506', 'Customer Support Team', '3'),
('10', 'Frustra se aut pecuniae studuisse aut imperiis aut opibus aut gloriae. Nullas enim consequuntur volu', '7582 Ethanwood Avenue, Warren, Michigan, United States, 48092', 'HR Team', '6'),
('11', 'Amorem efflorescere tantum, ut, etiamsi nulla sit utilitas ex amicitia, tamen ipsi amici propter se ', '4606 Vision Court, Tampa, Florida, United States, 33615', 'HR Team', '1'),
('12', 'Ferant, quid est cur dubitemus dicere et sapientiam propter voluptates expetendam.', '2561 Anniston Drive, Colorado Springs, Colorado, United States, 80951', 'HR Team', '2'),
('13', 'Dicta sunt ab iis quos probamus, eisque nostrum iudicium et nostrum scribendi ordinem adiungimus, qu', '3826 Princeton Place, Homestead, Florida, United States, 33034', 'Design Team', '2'),
('14', 'Duce natura nihil esse prosperum nisi voluptatem, nihil asperum nisi dolorem, de quibus neque deprav', '10479 Walterboro Lane, Columbus, Ohio, United States, 43220', 'Legal Team', '8'),
('15', 'Erudito, defensa est Epicuri sententia de.', '3551 James Road, Bradenton, Florida, United States, 34205', 'HR Team', '6'),
('16', 'Motus et impetus quo pertineant non intellegamus, tu tam egregios viros censes tantas res gessisse s', '13712 Galindo Place, Wichita Falls, Texas, United States, 76310', 'Marketing Team', '2'),
('17', 'Laudabilis eo referri, ut cum voluptate conectitur. Nam et praeterita et futura. Ut enim.', '1350 Trundle Terrace, Los Angeles, California, United States, 90094', 'HR Team', '3'),
('18', 'Ulla, quae sua natura aut sollicitare possit aut angere. Praeterea et appetendi.', '97 West Schwartz Blvd., Birmingham, Alabama, United States, 35220', 'Finance Team', '5'),
('19', 'Ut succumbere doloribus eosque humili animo inbecilloque ferre miserum.', '6076 Del Mar Drive, Indianapolis, Indiana, United States, 46254', 'Development Team', '5'),
('20', 'Ocurreret, si omnia dixi hausta e fonte naturae, si tota oratio nostra omnem sibi fidem sensibus.', '5046 Galewski Lane, Duluth, Georgia, United States, 30096', 'Legal Team', '4'),
('21', 'Neglegentur? Nam, ut sint opera, studio, labore meo doctiores cives mei, nec cum istis tantopere pug', '7220 Milagros Court, Lubbock, Texas, United States, 79410', 'Design Team', '1'),
('22', 'Cur in gravissimis rebus non delectet eos sermo patrius, cum idem fabellas Latinas ad verbum e Graec', '13384 Lystra Court, Washington, District of Columbia, United States, 20546', 'Legal Team', '6'),
('23', 'Fastidii delicatissimi. Mihi quidem videtur. Ac fieri potest, ut propemodum iustioribus utamur illis', '3383 Hammond Place, Indianapolis, Indiana, United States, 46266', 'Operations Team', '9'),
('24', 'Feramus, si minus, animo aequo e vita, cum ea non placeat, tamquam e theatro exeamus. Quibus rebus i', '6089 Saginaw Avenue, Wilkes Barre, Pennsylvania, United States, 18706', 'Marketing Team', '9'),
('25', 'Contra metum religionis et sedatio animi omnium rerum occultarum ignoratione sublata et moderatio na', '11538 Watercress Street, Tulsa, Oklahoma, United States, 74149', 'Operations Team', '7'),
('26', 'Quod quam magnum sit fictae veterum fabulae declarant, in quibus.', '10924 Allison Place, Little Rock, Arkansas, United States, 72231', 'Design Team', '4'),
('27', 'Errata ab Epicuro scriptum est et expedita distinctio.', '809 Dartford Terrace, Orlando, Florida, United States, 32808', 'Finance Team', '2'),
('28', 'Ut Epicuro placet, nihil dolere, primum tibi recte, Chrysippe, concessum est nihil ad Epicurum. Nam ', '435 Evelynton Loop, New York City, New York, United States, 10260', 'IT Team', '6'),
('29', 'Memoria torquentur, sapientes bona praeterita non meminerunt, praesentibus non fruuntur, futura modo', '4237 Knightsbridge Place, Hollywood, Florida, United States, 33028', 'Customer Support Team', '4'),
('30', 'Idcirco et hoc ipsum efficitur in amicitia, et amicitia cum voluptate vivatur. Quoniam autem id est ', '9961 Candlewick Court, Kent, Washington, United States, 98042', 'Development Team', '9'),
('31', 'Munere vitae optimum et verissimum sit, exquirere? An, partus ancillae sitne in fructu habendus, dis', '3818 Pilar Place, Nashville, Tennessee, United States, 37245', 'Development Team', '4'),
('32', 'Neque maiorem voluptatem ex hoc percipiatur, quod videamus esse finitum. In dialectica autem vestra ', '14414 Jodphur Lane, Las Vegas, Nevada, United States, 89155', 'Operations Team', '2'),
('33', 'Modo quae dicat ille bene noris. Nisi mihi Phaedrum, inquam, tu mentitum aut Zenonem putas, quorum u', '12065 Jim Street, Rochester, Minnesota, United States, 55905', 'Finance Team', '6'),
('34', 'Dolorem et voluptatem; illud enim ipsum, quod quibusdam medium videretur, cum omni dolore careret, n', '9251 Hoffman Court, Rochester, Minnesota, United States, 55905', 'HR Team', '7'),
('35', 'Tamen necessariae, tertium, quae nec naturales nec necessariae. Quarum ea ratio est, ut omne, quo of', '7767 Enright Place, Newark, New Jersey, United States, 07104', 'Development Team', '9'),
('36', 'Est, sic amicitiam negant posse a voluptate aut in dolore. Omnis autem privatione doloris putat Epic', '7765 Beaumont Terrace, Seattle, Washington, United States, 98166', 'HR Team', '8'),
('37', 'Reliquaque eiusdem generis et legimus libenter et legemus --, haec, quae de philosophia litteris man', '8939 Sunset Pointe Blvd., Saint Louis, Missouri, United States, 63131', 'Development Team', '2'),
('38', 'Sit, sed stare etiam oportet in eo, quod semel admissum coerceri reprimique non potest, ut non modo ', '14517 Kayla Court, Des Moines, Iowa, United States, 50320', 'Finance Team', '8'),
('39', 'Res gessisse sine causa? Quae fuerit causa, mox videro; interea.', '8103 Santana Way, Philadelphia, Pennsylvania, United States, 19172', 'Operations Team', '9'),
('40', 'Animi omnium rerum occultarum ignoratione sublata et moderatio natura cupiditatum generibusque earum', '5310 Encino Lane, Saginaw, Michigan, United States, 48604', 'Design Team', '6');

