USE ArtPlatformDB;
INSERT INTO Artist (`artist_id`, `name`, `contact_info`, `team_id`) VALUES
('1', 'Kristi Rapaport', 'Sit. Erit enim iam de.', '33'),
('2', 'Kristien Hamfleet', 'Sententiam, quid est cur verear, ne ad eam non possim accommodare Torquatos nostros? Quos tu paulo ante cum memoriter, tum etiam erga nos amice et benivole collegisti, nec me tamen laudandis maioribus', '1'),
('3', 'Valle Laven', 'Se habeat. Nam si ea sola voluptas esset, quae quasi saxum Tantalo.', '18'),
('4', 'Cathleen Sellors', 'Potest. Atqui pugnantibus et contrariis studiis consiliisque semper utens nihil.', '38'),
('5', 'Uta Hollyar', 'Ipsos diligamus, idcirco et hoc ipsum efficitur in amicitia, et amicitia cum voluptate vivatur. Quoniam autem id est vel summum bonorum vel ultimum vel extremum -- quod et scripta multa sunt, sic ut p', '22'),
('6', 'Cheryl Willars', 'Illo, recta et honesta quae sint, ea facere ipsa per se esse fugiendum. Itaque aiunt hanc quasi naturalem atque insitam in animis.', '12'),
('7', 'Francine Lerven', 'Debilitatem animi multi parentes, multi amicos, non nulli patriam, plerique autem se ipsos diligant. Quod et posse fieri intellegimus et saepe disserui, Latinam linguam non modo fautrices fidelissimae', '9'),
('8', 'Elfie Goldbourn', 'Obligantur. Qui autem ita frui volunt voluptatibus, ut nulli propter eas consequantur dolores, et qui suum iudicium retinent, ne voluptate victi faciant id, quod maxime placeat.', '40'),
('9', 'Sigmund Moodie', 'Litteris mandaremus, fore ut hic noster labor in varias reprehensiones incurreret. Nam quibusdam, et iis quidem non admodum flagitem. Re mihi non aeque satisfacit, et quidem locis.', '26'),
('10', 'Lexy Glyssanne', 'In disputando pertinaces indignae philosophia mihi videri solent. Tum Torquatus: Prorsus, inquit, assentior; neque enim disputari sine reprehensione nec cum istis tantopere.', '15'),
('11', 'Violante Riply', 'Utilitas ex amicitia, tamen ipsi amici propter se ipsos amentur. Etenim si loca, si fana, si urbes, si gymnasia, si.', '25'),
('12', 'Kristofor Woodberry', 'Et secunda iucunde ac suaviter meminerimus. Sed cum ea, quae senserit ille, tibi non vera videantur. Vide, quantum, inquam, fallare, Torquate. Oratio me istius philosophi non offendit; nam et ipsa.', '11'),
('13', 'Calypso Diffley', 'Sentiunt frustra se aut pecuniae studuisse aut imperiis aut opibus aut gloriae. Nullas enim consequuntur voluptates, quarum potiendi spe inflammati multos labores magnosque susceperant. Ecce autem ali', '24'),
('14', 'Ward Kunrad', 'His esse potiora. Quid est enim in vita tantopere quaerendum quam cum omnia in philosophia.', '31'),
('15', 'Tommy Plumptre', 'Nec fortitudinem patientiamque laudari suo nomine, sed illas reici, quia dolorem pariant, has optari, quia voluptatem. Iustitia restat, ut de utilitatibus, nihil ut de commodis suis cogitarent? At.', '4'),
('16', 'Wait Harrowing', 'Sic amicitiae non posse reperiri. Quapropter si ea, quae praeterierunt, acri animo et attento intuemur, tum fit ut aegritudo sequatur, si illa mala sint, laetitia, si bona. O praeclaram beate.', '28'),
('17', 'Juditha Guiver', 'Atomorum inter se, ex quo vitam amarissimam.', '7'),
('18', 'Odelia Clapp', 'Quod maluisti, te, cum ad me accedis, saluto: ''chaere,'' inquam, ''Tite!'' lictores, turma omnis chorusque: ''chaere, Tite!'' hinc hostis mi Albucius, hinc inimicus. Sed.', '14'),
('19', 'Cordelie Otteridge', 'Culpa, qui officia deserunt mollit anim id est quo melius viveremus, eas ergo artes persequeretur, vivendi artem tantam tamque et operosam et perinde fructuosam relinqueret? Non ergo Epicurus inerudit', '23'),
('20', 'Jolee Sussams', 'Vita sine amicis insidiarum et metus plena sit, ratio ipsa monet amicitias comparare, quibus partis confirmatur animus et excelsus omni est liber cura et angore, cum et tibi probatus videretur et iis,', '39'),
('21', 'Sibbie Finkle', 'Quarum summum erat in utroque studium, deinde Torquatus: Quoniam nacti te, inquit, sumus aliquando.', '34'),
('22', 'Betsy Harefoot', 'De re cum sit inter doctissimos summa dissensio, quis alienum putet eius.', '37'),
('23', 'Flory Lamden', 'Voluptatem, aut cum Latinis tertio consulatu conflixisse apud Veserim propter voluptatem; quod vero.', '20'),
('24', 'Anissa Piesold', 'Dicemus, sed quia non numquam eius.', '36'),
('25', 'Wanids Winger', 'Explicavi, inquit, sententiam meam, et eo quidem consilio, tuum iudicium ut cognoscerem, quoniam mihi ea facultas, ut id apte fieri possit, ut ab ipsis, qui eam disciplinam.', '19'),
('26', 'Wally Stapells', 'Quamquam te quidem video minime esse deterritum. Quae cum dixisset, Explicavi, inquit, sententiam meam, et eo.', '27'),
('27', 'Sylvester Shearmur', 'Rerum tenebimus, servata illa, quae quasi titillaret sensus, ut ita.', '16'),
('28', 'Gael Loosmore', 'Mortem, de diis inmortalibus supplicii causa importari putant.', '5'),
('29', 'Sigmund Petyankin', 'Anteponant iis, quae et a formidinum terrore vindicet et ipsius fortunae modice ferre doceat iniurias et omnis monstret vias, quae ad quietem.', '8'),
('30', 'Denni Vallack', 'Veniamus. Quid tibi, Torquate, quid huic Triario litterae, quid historiae cognitioque rerum, quid poetarum evolutio, quid tanta tot versuum memoria voluptatis affert? Nec mihi illud dixeris: ''Haec eni', '29'),
('31', 'Maisie Kill', 'Nos ea, quae dices, libenter assentiar. Probabo, inquit, modo.', '3'),
('32', 'Carri Cartwight', 'Putas, quorum utrumque audivi, cum miraretur ille quidem utrumque, Phaedrum autem.', '21'),
('33', 'Seymour Wreiford', 'Necessarius de amicitia, quam, si voluptas esset bonum, desideraret.'' -- Ita credo. -- ''Non est igitur voluptas bonum.'' Hoc ne statuam quidem dicturam pater aiebat, si.', '10'),
('34', 'Fairleigh Kubiak', 'Tempor incididunt ut labore et dolore disputandum putant. Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae laudatur', '2'),
('35', 'Sapphire Harraway', 'Plerique autem se ipsos amentur. Etenim si loca, si fana, si urbes, si gymnasia, si campum, si canes, si equos, si ludicra exercendi aut venandi consuetudine adamare solemus, quanto id in hominum cons', '35'),
('36', 'Ervin Mum', 'Dicat ille bene noris. Nisi mihi Phaedrum, inquam, tu mentitum aut Zenonem putas, quorum utrumque audivi, cum mihi nihil sane praeter sedulitatem probarent, omnes mihi Epicuri sententiae satis notae s', '6'),
('37', 'Pall Gozard', 'Tibi parum videtur eruditus, ea.', '13'),
('38', 'Zara Glyssanne', 'Leniter arridens: Tu quidem, inquit, totum Epicurum paene.', '17'),
('39', 'Sinclare Santo', 'Studiis consiliisque semper utens nihil quieti videre, nihil tranquilli potest. Quodsi vitam omnem perturbari videmus errore et inscientia, sapientiamque esse solam, quae nos exhorrescere metu non sin', '30'),
('40', 'Rosemaria Lapping', 'Iudicari, sed animo etiam ac ratione intellegi posse et voluptatem pleniorem efficit. Itaque non ob ea solum incommoda, quae eveniunt inprobis, fugiendam inprobitatem putamus, sed multo magis vita.', '32');

