USE ArtPlatformDB;

INSERT INTO Schedule (`schedule_id`, `message`, `schedule_datetime`, `artist_id`) VALUES
('1', 'Do eiusmod tempor incididunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aut', '2025-04-10 04:04:08', '38'),
('2', 'Minuendas vitae molestias accessio potest fieri, quanta ad augendas, cum conscientia factorum.', '2024-10-13 07:27:44', '8'),
('3', 'Certamen est? Tuo vero id quidem, inquam, arbitratu. Sic faciam igitur, inquit: unam rem explicabo, eamque maximam, de physicis alias, et quidem locis pluribus. Sed quot.', '2025-04-04 14:37:43', '35'),
('4', 'Admirer, cur in gravissimis rebus non delectet eos sermo patrius, cum idem fabellas Latinas ad verbum e Graecis expressas non inviti.', '2024-09-08 04:25:49', '5'),
('5', 'Torquato, homine omni doctrina erudito, defensa est Epicuri sententia de voluptate, nihil scilicet novi, ea tamen, quae te ipsum probaturum esse confidam. Certe, inquam, pertinax non ero tibique, si m', '2024-09-20 01:20:29', '39'),
('6', 'Qui hoc primus cognomen invenerit, aut torquem illum hosti detraxisse, ut aliquam ex eo perciperet corpore voluptatem, aut cum Latinis tertio consulatu conflixisse apud Veserim propter voluptatem; cum', '2024-05-01 17:01:13', '24'),
('7', 'Amicitia dicenda sunt. Praeclare enim Epicurus his paene verbis: ''Eadem'', inquit, ''scientia confirmavit animum, ne quod aut sempiternum aut diuturnum timeret malum, quae perspexit in hoc ipso vitae sp', '2024-11-11 14:34:09', '20'),
('8', 'Quo ignorare vos arbitrer, sed ut ratione et via procedat.', '2025-03-09 14:48:09', '25'),
('9', 'Tamquam adversarium aliquem convincere. Accurate autem quondam a L. Torquato, homine omni doctrina erudito, defensa est Epicuri sententia de voluptate, a meque ei responsum, cum C. Triarius, in primis', '2024-10-20 20:06:37', '29'),
('10', 'Igitur Epicuri non probo, tum illud in primis, quod, cum in rerum natura cognita levamur superstitione, liberamur mortis metu, non conturbamur ignoratione rerum, e qua ipsa horribiles existunt saepe f', '2024-08-21 17:20:26', '7'),
('11', 'Platonis, Aristoteli, Theophrasti orationis ornamenta neglexerit. Nam illud quidem adduci vix possum, ut ea, quae dixi, sole ipso illustriora et clariora sunt, si omnia dixi hausta e fonte naturae, si', '2024-11-23 04:22:46', '34'),
('12', 'Expleantur; ne naturales quidem multa desiderant, propterea quod ipsa natura, ut ait ille, sciscat et probet, id est quo melius viveremus, eas ergo artes persequeretur, vivendi artem tantam tamque et ', '2025-03-28 20:37:39', '22'),
('13', 'Peccant, cum e quibus haec efficiantur.', '2024-10-21 20:56:08', '30'),
('14', 'Quarum ea ratio est, ut meminerit maximos morte finiri, parvos multa habere intervalla requietis, mediocrium nos esse dominos, ut, si tolerabiles sint, feramus, si minus, animo aequo e vita, cum ea no', '2025-01-23 01:57:32', '32'),
('15', 'Propter voluptates expetendam et dolorem ipsum per se esse fugiendum. Itaque aiunt hanc quasi naturalem atque insitam in animis nostris inesse notionem, ut alterum esse appetendum, alterum aspernandum', '2025-04-10 01:53:41', '10'),
('16', 'Numquam in sententia permanentes, quas ob causas in eorum vita nulla est intercapedo.', '2024-06-26 22:15:27', '6'),
('17', 'Utens nihil quieti videre, nihil tranquilli potest. Quodsi corporis gravioribus morbis vitae iucunditas impeditur, quanto magis animi morbis impediri necesse est! Animi autem voluptates et dolores nas', '2024-11-10 18:15:54', '27'),
('18', 'Hoc statu praestabiliorem aut magis expetendum possimus dicere? Inesse enim necesse est in eo, quod sit iudicatum. Plerique.', '2024-05-07 06:20:05', '15'),
('19', 'Tamen necessariae, tertium, quae nec naturales nec necessariae. Quarum ea ratio est, ut.', '2025-03-22 12:04:20', '37'),
('20', 'Si ludicra exercendi aut venandi consuetudine adamare solemus, quanto id in voluptate velit esse, quam nihil praetermittatur quod vitam adiuvet, quo facilius id, quod ipsi statuerunt, non possunt, con', '2024-07-23 06:07:35', '17'),
('21', 'Epicuri disciplinam placet an de una voluptate quaeri, de.', '2025-01-15 19:12:14', '21'),
('22', 'Qui e nostris aliter existimant, quos quidem video esse multos, sed imperitos --, quamquam autem et praeterita et futura. Ut enim medicorum scientiam non.', '2024-04-14 12:13:08', '31'),
('23', 'Ipso parum vidit, deinde hoc quoque.', '2024-10-02 13:41:12', '18'),
('24', 'Quam a nobis philosophia defensa et collaudata est, cum id, quod sentiant.', '2024-06-14 05:35:00', '26'),
('25', 'Clarorum hominum factis illustribus et gloriosis satis hoc loco dictum sit. Erit enim iam de omnium virtutum cursu ad voluptatem proprius disserendi locus. Nunc autem explicabo, voluptas ipsa quae qua', '2024-12-22 03:07:01', '19'),
('26', 'Cum a philosophis compluribus permulta dicantur, cur nec voluptas in bonis sit numeranda nec in discordia dominorum domus; quo minus omnes mea legant. Utinam esset ille Persius, Scipio vero et.', '2024-09-28 05:35:08', '13'),
('27', 'Causa, nollem me ab eo nos abducat? Sin laboramus, quis est, qui alienae modum statuat industriae? Nam ut Terentianus Chremes non.', '2024-12-21 01:34:59', '16'),
('28', 'Sapientiam, temperantiam, fortitudinem copulatas esse docui cum voluptate, ut ab ipsis, qui eam disciplinam probant, non soleat accuratius explicari; verum enim invenire volumus, non tamquam adversari', '2025-01-16 15:34:39', '28'),
('29', 'Etiam Athenis, ut e patre.', '2024-06-23 23:32:27', '12'),
('30', 'Ipso parum vidit, deinde hoc quoque alienum; nam ante Aristippus.', '2025-01-05 00:50:22', '2'),
('31', 'Appellat, id est in voluptate.', '2025-03-21 07:09:59', '33'),
('32', 'Hoc, qui eum unum secutus esset, nollem vituperatum. Iam in altera philosophiae parte. Quae est quaerendi ac disserendi, quae logikh dicitur, iste vester plane, ut mihi quidem depravare videatur. Ille', '2024-10-07 06:55:56', '40'),
('33', 'Reperietur. Nam neque laborum perfunctio neque perpessio dolorum per se ipsas tam expetendas, quam nostras expeteremus, quo loco videtur quibusdam stabilitas amicitiae vacillare, tuentur tamen eum loc', '2025-03-25 04:22:22', '11'),
('34', 'Eligendi optio, cumque nihil impedit, quo minus animus a se ipse dissidens secumque discordans gustare partem ullam liquidae voluptatis et liberae potest. Atqui pugnantibus et contrariis studiis consi', '2024-06-02 15:27:47', '4'),
('35', 'Constituamus aliquem magnis, multis, perpetuis fruentem et animo et corpore voluptatibus nullo dolore nec impediente nec inpendente, quem tandem hoc statu praestabiliorem aut magis expetendum possimus', '2024-12-24 12:32:21', '1'),
('36', 'Eam causam non multo maiores esse et voluptates et dolores.', '2024-12-31 07:05:15', '36'),
('37', 'Ut dixi, ad lineam, hunc naturalem esse omnium corporum motum. Deinde ibidem homo acutus, cum illud.', '2024-10-24 11:56:26', '14'),
('38', 'Scaevolam M''.que Manilium, ab iisque M. Brutus dissentiet -- quod et scripta multa sunt.', '2024-09-30 03:34:34', '3'),
('39', 'Sentiant non esse faciendum, ii voluptatem maximam adipiscuntur praetermittenda voluptate. Idem etiam dolorem saepe perpetiuntur, ne, si amicitiam.', '2025-02-14 21:55:57', '9'),
('40', 'Homini erudito in geometriaque perfecto, huic pedalis fortasse; tantum enim esse censet, quantus videtur, vel paulo aut maiorem aut minorem. Ita, quae mutat, ea corrumpit, quae sequitur sunt tota Demo', '2024-04-25 15:39:43', '23'),
('41', 'Quantum efficere possimus, molestia liberemus. Ut enim ad sapientiam perveniri potest, non.', '2024-11-09 08:48:55', '26'),
('42', 'Ei responsum, cum C. Triarius, in.', '2024-08-05 00:56:29', '38'),
('43', 'Cum conscientia factorum, tum poena legum odioque civium? Et tamen in quibusdam neque.', '2024-08-09 01:25:42', '13'),
('44', 'Ex utraque parte audita pronuntiaret eum non talem videri fuisse in imperio, quales eius maiores fuissent, et in conspectum suum venire vetuit, numquid tibi videtur de.', '2025-02-18 08:08:07', '24'),
('45', 'Et clariora sunt, si omnia dixi hausta e fonte naturae, si tota oratio nostra omnem sibi fidem sensibus confirmat, id est voluptatem. Homines optimi non intellegunt totam rationem everti, si ita res s', '2024-05-19 14:04:31', '16'),
('46', 'Modo non impediri rationem amicitiae, si summum bonum in voluptate ponit, quod summum bonum diceret, primum in eo quoque elaborare, ut sint opera, studio.', '2024-11-09 03:55:10', '22'),
('47', 'Videantur. Vide, quantum, inquam, fallare, Torquate. Oratio me istius philosophi non offendit; nam et complectitur verbis, quod vult, et dicit plane, quod intellegam; et tamen ego a philosopho, si aff', '2024-12-16 17:22:41', '37'),
('48', 'Pecuniae studuisse aut imperiis aut opibus aut gloriae. Nullas enim consequuntur voluptates, quarum potiendi spe inflammati multos labores magnosque susceperant. Ecce autem alii minuti et angusti aut ', '2024-05-03 17:52:27', '3'),
('49', '--, quod ipsum nullam ad aliam rem, ad id omnia referri oporteat, ipsum autem nusquam.', '2025-03-06 19:27:07', '21'),
('50', 'Non possim accommodare Torquatos nostros? Quos tu paulo.', '2024-10-09 11:41:40', '12');

